### ISSUE TITLE
Colors wrong when setting by RGB values

### ISSUE THREAD

**Issue by adammhaile** [Sh4d/LPD8806#2]
I just picked up some LPD8806 LED strips and hooked them up to my RPi.
In the demo, the color wheel works perfectly but when I try to set colors other than Red, Green or Blue individually, the colors output are wrong.

For example, if I ran through the colors as follows (with updates in between of course):
led.set(255,0,0)      //red
led.set(255,127,0)  //orange
led.set(255,255,0)  //yellow
led.set(0,255,0)      //green
led.set(0,0,255)      //blue
led.set(111,0,255)  //indigo
led.set(143,0,255)  //violet

I end up getting something more like; red, pink, violet, blue, green, yellow.
It's almost (but not quite) in perfect reverse order.

Like I said, the color wheel works perfectly and if I, for example, enabled only 7 LEDs, it would be in perfect rainbow order. But that code seems to be calculation the values differently.

Either way, it seems like somehow the individual RGB values are not getting set quite right.

Any thoughts?

**Comment by tekket** [comment]
Ive come across this issue myself.  It seems there is a certain manufacturer which put the strip together differently then most others.
Adafruit's strips which the LPD8806 library was created from has the color order RBG.  So their library they created adjusts for this,  Some other manufacturers re did the strip so that its actually RGB, so the adafruit strips are then backwards.

To fix I would update switch the G and B on the lines
            self.buffer[led][0] = self.gamma[g]
            self.buffer[led][1] = self.gamma[r]
            self.buffer[led][2] = self.gamma[b]
to
            self.buffer[led][0] = self.gamma[b]
            self.buffer[led][1] = self.gamma[r]
            self.buffer[led][2] = self.gamma[g]

There may be a better way, but thats what I would try first.

**Comment by adammhaile** [comment]
That was it! Thank you!
And yeah... my RGB strips are not from Adafruit. 
I'm working on a large project which will need a lot of these, so I went straight to a manufacturer to same some cash. The LED strips I got are really nice quality, but obviously have the lines flipped from the ones that Adafruit sells.

Per the LPD8806 spec, I wonder which one is technically correct? Adafruit or the other suppliers?

**Comment by tekket** [comment]
I think adafruit was the first and only one to reverse engineer the LPD8806 chip, so their library is based on their manufacturer which has the bytes in a certain way. I think most work has been derived from theirs regarding what bytes control what colors.

hope this isnt against any of the terms but i've ordered 15M from a site direct for $14/m with no problems,and arrived in 2 days from gree-leds dot com  Best price ive seen anywhere and great service.(i have no affiliation with them but just a good deal)

**Comment by adammhaile** [comment]
Figures.
That's a pretty good price. Do you know yet if they are in the "Adafruit Order"?

**Comment by tekket** [comment]
Yes. identical to adafruit.  email me tekket3 at gmail.com and we can discuss offline if you like.

**Comment by zpeleg** [comment]
To anyone coming here now and wondering what the hell is that code that tekket wrote earlier, there's a better way now. Look at the RGB calibrate example.
https://github.com/FastLED/FastLED/wiki/Rgb-calibration

**Comment by adammhaile** [comment]
Oh wow... blast from the past :) In the 4 years since then, I've forked this library into BiblioPixel and actually have that RGB calibration built in: https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/animation.py#L436
